// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chitchat_Join_FullMethodName        = "/Chitchat/Join"
	Chitchat_Leave_FullMethodName       = "/Chitchat/Leave"
	Chitchat_PostMessage_FullMethodName = "/Chitchat/PostMessage"
)

// ChitchatClient is the client API for Chitchat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitchatClient interface {
	Join(ctx context.Context, in *User, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	Leave(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
	PostMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type chitchatClient struct {
	cc grpc.ClientConnInterface
}

func NewChitchatClient(cc grpc.ClientConnInterface) ChitchatClient {
	return &chitchatClient{cc}
}

func (c *chitchatClient) Join(ctx context.Context, in *User, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chitchat_ServiceDesc.Streams[0], Chitchat_Join_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[User, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chitchat_JoinClient = grpc.ServerStreamingClient[Message]

func (c *chitchatClient) Leave(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chitchat_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitchatClient) PostMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chitchat_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChitchatServer is the server API for Chitchat service.
// All implementations must embed UnimplementedChitchatServer
// for forward compatibility.
type ChitchatServer interface {
	Join(*User, grpc.ServerStreamingServer[Message]) error
	Leave(context.Context, *User) (*Empty, error)
	PostMessage(context.Context, *Message) (*Empty, error)
	mustEmbedUnimplementedChitchatServer()
}

// UnimplementedChitchatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitchatServer struct{}

func (UnimplementedChitchatServer) Join(*User, grpc.ServerStreamingServer[Message]) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedChitchatServer) Leave(context.Context, *User) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedChitchatServer) PostMessage(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedChitchatServer) mustEmbedUnimplementedChitchatServer() {}
func (UnimplementedChitchatServer) testEmbeddedByValue()                  {}

// UnsafeChitchatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitchatServer will
// result in compilation errors.
type UnsafeChitchatServer interface {
	mustEmbedUnimplementedChitchatServer()
}

func RegisterChitchatServer(s grpc.ServiceRegistrar, srv ChitchatServer) {
	// If the following call pancis, it indicates UnimplementedChitchatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chitchat_ServiceDesc, srv)
}

func _Chitchat_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChitchatServer).Join(m, &grpc.GenericServerStream[User, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chitchat_JoinServer = grpc.ServerStreamingServer[Message]

func _Chitchat_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).Leave(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chitchat_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).PostMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Chitchat_ServiceDesc is the grpc.ServiceDesc for Chitchat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chitchat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chitchat",
	HandlerType: (*ChitchatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Leave",
			Handler:    _Chitchat_Leave_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _Chitchat_PostMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _Chitchat_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
