// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chitchat_Join_FullMethodName    = "/Chitchat/Join"
	Chitchat_Leave_FullMethodName   = "/Chitchat/Leave"
	Chitchat_Message_FullMethodName = "/Chitchat/Message"
)

// ChitchatClient is the client API for Chitchat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitchatClient interface {
	Join(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error)
	Leave(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
	Message(ctx context.Context, in *UserMessage, opts ...grpc.CallOption) (*Empty, error)
}

type chitchatClient struct {
	cc grpc.ClientConnInterface
}

func NewChitchatClient(cc grpc.ClientConnInterface) ChitchatClient {
	return &chitchatClient{cc}
}

func (c *chitchatClient) Join(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Chitchat_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitchatClient) Leave(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chitchat_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitchatClient) Message(ctx context.Context, in *UserMessage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chitchat_Message_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChitchatServer is the server API for Chitchat service.
// All implementations must embed UnimplementedChitchatServer
// for forward compatibility.
type ChitchatServer interface {
	Join(context.Context, *Empty) (*User, error)
	Leave(context.Context, *User) (*Empty, error)
	Message(context.Context, *UserMessage) (*Empty, error)
	mustEmbedUnimplementedChitchatServer()
}

// UnimplementedChitchatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitchatServer struct{}

func (UnimplementedChitchatServer) Join(context.Context, *Empty) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedChitchatServer) Leave(context.Context, *User) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedChitchatServer) Message(context.Context, *UserMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedChitchatServer) mustEmbedUnimplementedChitchatServer() {}
func (UnimplementedChitchatServer) testEmbeddedByValue()                  {}

// UnsafeChitchatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitchatServer will
// result in compilation errors.
type UnsafeChitchatServer interface {
	mustEmbedUnimplementedChitchatServer()
}

func RegisterChitchatServer(s grpc.ServiceRegistrar, srv ChitchatServer) {
	// If the following call pancis, it indicates UnimplementedChitchatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chitchat_ServiceDesc, srv)
}

func _Chitchat_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).Join(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chitchat_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).Leave(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chitchat_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitchatServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chitchat_Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitchatServer).Message(ctx, req.(*UserMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Chitchat_ServiceDesc is the grpc.ServiceDesc for Chitchat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chitchat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chitchat",
	HandlerType: (*ChitchatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Chitchat_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _Chitchat_Leave_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _Chitchat_Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
